version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: go-crud-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - crud-network

  app:
    build: .
    container_name: go-crud-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: apiuser
      DB_PASSWORD: apipassword
      DB_NAME: userdb
    networks:
      - crud-network

  frontend:
    build: ./frontend
    container_name: go-crud-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - crud-network

volumes:
  mysql_data:

networks:
  crud-network:
    driver: bridge